[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18", VITE_CLERK_PUBLISHABLE_KEY = "" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"